version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pixsy-api"
s3_bucket = "pixsy-bucket"
region = "eu-central-1"
profile = "personal"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
