AWSTemplateFormatVersion: 2010-09-09
Description: >-
  pixsy-api
Transform:
- AWS::Serverless-2016-10-31
Resources:
  pixsyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "Prod"
      Cors: 
        AllowMethods: "'GET, HEAD, OPTIONS'"
        AllowOrigin: "'*'"
        MaxAge: "'1200'"
        AllowHeaders: "'Content-Type, Authorization'"
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
        - ResourcePath: /topic/{topic_name}
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
  getCollectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-collections.getCollectionsHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 900
      Description: A simple example includes a HTTP get method to get all items from
        a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref pixsyApi
            Path: /
            Method: GET

  getPhotosInACollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-photos-in-a-collection.getPhotosInACollectionHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 900
      Description: A simple example includes a HTTP get method to get one item by
        id from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref pixsyApi
            Path: /topic/{topic_name}
            Method: GET
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${pixsyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
