AWSTemplateFormatVersion: 2010-09-09
Description: >-
  pixsy-api
Transform:
- AWS::Serverless-2016-10-31
Resources:
  getCollectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-collections.getCollectionsHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 1000
      Description: A simple example includes a HTTP get method to get all items from
        a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  getPhotosInACollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-photos-in-a-collection.getPhotosInACollectionHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by
        id from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{topic_name}
            Method: GET

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
